networks:
  dev:
    driver: bridge
volumes:
  firebase-emulators-cache:
  clarinet_var_lib_docker:
services:
  dev:
    container_name: dev
    image: ${BUILDER_IMAGE}
    env_file:
      - .env
    environment:
      HOST_PWD: ${PWD:-/workspaces/refactored-winner}
      MAKE_DEV_ON_START: ${MAKE_DEV_ON_START:-true}
    volumes:
      - ${PWD:-/workspaces/refactored-winner}:${PWD:-/workspaces/refactored-winner}:cached
      - /var/run/docker.sock:/var/run/docker.sock
      - /dev:/dev
      - /lib/modules:/lib/modules:ro
    privileged: true
    cap_add:
      - SYS_ADMIN
      - NET_ADMIN
    working_dir: ${PWD:-/workspaces/refactored-winner}
    command: |
      bash -c '
      make docker-sock
      if [ "$${MAKE_DEV_ON_START}" = "true" ] ; then
        make dev
        if [ "$${MAKE_LOCAL_APPLICATION_TESTS_RUN_ON_START}" = "true" ] ; then
          until make local-application-tests-check-env ; do
            echo "[application-tests] Waiting for environment to be ready..."
            sleep 5
          done
          make application-tests-robot-framework-all-run
        fi
      fi
      sleep infinity
      '
    networks:
      dev:
        aliases:
          - devcontainer

  application-backend:
    restart: unless-stopped
    image: ${APPLICATION_BACKEND_IMAGE:-europe-west1-docker.pkg.dev/moov-438615/docker-repository/utrade:application-backend-latest}
    build:
      context: ..
      dockerfile: application/backend/Dockerfile
      args:
        builder_image: ${BUILDER_IMAGE}

    env_file:
      - .env
    environment:
      GOOGLE_APPLICATION_CREDENTIALS: ${GOOGLE_APPLICATION_CREDENTIALS:-/workspaces/refactored-winner/.devcontainer/gcloud/infra/application_default_credentials.json}
      FIREBASE_PROJECT_ID: ${FIREBASE_PROJECT_ID:-moov}
      UI_CONFIG_FIREBASE_SECRET_ID: ${UI_CONFIG_FIREBASE_SECRET_ID:-projects/moov-dev-439608/secrets/firebase-config-web/versions/2}
      UI_CONFIG_GOOGLEMAPS_SECRET_ID: ${UI_CONFIG_GOOGLEMAPS_SECRET_ID:-projects/moov-dev-439608/secrets/google-maps-api-key/versions/1}
      VAULT_ADDR: http://vault-dev:8200
      VAULT_TOKEN: root
    volumes:
      - ${PWD:-/workspaces/refactored-winner}:${PWD:-/workspaces/refactored-winner}:cached
    networks:
      - dev

  firebase-emulators:
    container_name: firebase-emulators
    image: ${FIREBASE_EMULATORS_IMAGE:-europe-west1-docker.pkg.dev/moov-dev-439608/docker-repository-public/moov-dev-439608:firebase-emulators-latest}
    # Cannot build while Dockerfile base image (see FROM ...) is using new local builder image (for conveniance and accuracy) that could not be pulled yet.
    # build: NOT
    env_file:
      - .env
    environment:
      FIREBASE_AUTH_EMULATOR_HOST: http://localhost:9099
      FIRESTORE_EMULATOR_HOST: http://localhost:8090
    volumes:
      - ${HOST_PWD:-${PWD:-/workspaces/refactored-winner}}:${PWD:-/workspaces/refactored-winner}:cached
      # - firebase-emulators-cache:/home/devuser/.cache/firebase/emulators
    working_dir: ${PWD:-/workspaces/refactored-winner}

    networks:
      dev:

  clarinet-devnet:
    container_name: clarinet-devnet
    privileged: true
    tty: true
    image: ${CLARINET_DEVNET_IMAGE:-europe-west1-docker.pkg.dev/moov-dev-439608/docker-repository-public/moov-dev-439608:clarinet-latest}
    # Cannot build while Dockerfile base image (see FROM ...) is using new local builder image (for conveniance and accuracy) that could not be pulled yet.
    # build: NOT
    env_file:
      - .env
    environment:
      DOCKER_HOST: "unix:///run/user/1000/docker.sock"
    volumes:
      - /dev:/dev
      - /lib/modules:/lib/modules
      - ${HOST_PWD:-${PWD:-/workspaces/refactored-winner}}:${PWD:-/workspaces/refactored-winner}:cached
    cap_add:
      - NET_ADMIN
      - SYS_ADMIN
    working_dir: ${PWD:-/workspaces/refactored-winner}/local/clarinet-devnet
    command: |
      bash -c '
      set -eu
      make -C ../.. local-clarinet-devnet-start
      sleep infinity
      '
    networks:
      dev:
  android-studio:
    container_name: android-studio
    cap_add:
      - SYS_ADMIN
    image: ${ANDROID_STUDIO_IMAGE:-europe-west1-docker.pkg.dev/moov-dev-439608/docker-repository-public/moov-dev-439608:android-studio-latest}
    env_file:
      - .env
    environment:
      PROJECT_DIR: ${PWD:-/workspaces/refactored-winner}
      DISPLAY_RESOLUTION: "${DISPLAY_RESOLUTION:-1920x1080}"
      CHROME_LOG_FILE: /tmp/chrome_debug.log
      ANDROID_STUDIO_LOG_LEVEL: DEBUG
    # deploy:
    #   resources:
    #     reservations:
    #       devices:
    #         - driver: nvidia
    #           count: all
    #           capabilities: [gpu]
    privileged: true
    volumes:
      - ${PWD:-/workspaces/refactored-winner}:${PWD:-/workspaces/refactored-winner}:cached
    devices:
      - /dev/kvm
    shm_size: "8gb"
    group_add:
      - render
      - kvm
      - sgx
    working_dir: ${PWD:-/workspaces/refactored-winner}/application/mobile
    networks:
      dev:
    command: |
      bash -c '

      set -eu

      # For using Android Studio with emulator in a graphical session
      [ "$${LOCAL_ANDROID_STUDIO_ON_START}" = "true" ] && \
        android-studio.sh &

      # For automatic e2e application/tests 
      [ "$${LOCAL_ANDROID_STUDIO_APPIUM_EMULATOR_AVD_ON_START}" = "true" ] && \
        appium-emulator-avd.sh &

      sleep infinity
      '
  vault-dev:
    container_name: vault-dev
    # image: hashicorp/vault:1.19
    image: ${VAULT_DEV_IMAGE:-europe-west1-docker.pkg.dev/moov-dev-439608/docker-repository-public/moov-dev-439608:vault-dev-latest}

    cap_add:
      - IPC_LOCK
    environment:
      VAULT_DATA: ${PWD:-/workspaces/refactored-winner}/local/.containers/vault/file
      VAULT_CONFIG: ${PWD:-/workspaces/refactored-winner}/local/.containers/vault/config
      VAULT_AUDIT: ${PWD:-/workspaces/refactored-winner}/local/.containers/vault/audit
      VAULT_ADDR: http://0.0.0.0:8200
      VAULT_DEV_ROOT_TOKEN_ID: root
      VAULT_DEV_LISTEN_ADDRESS: "0.0.0.0:8200"
    volumes:
      - ${HOST_PWD:-${PWD:-/workspaces/refactored-winner}}:${PWD:-/workspaces/refactored-winner}:cached
    working_dir: ${PWD:-/workspaces/refactored-winner}
    command: |
      bash -c '
      set -eu
      ./local/backend-application-vault-init.sh
      sleep infinity
      '
    networks:
      dev:

  application-tests:
    container_name: application-tests
    image: ${APPLICATION_TESTS_IMAGE:-europe-west1-docker.pkg.dev/moov-dev-439608/docker-repository-private/moov-dev-439608:application-tests-latest}
    environment:
      APPLICATION_BACKEND_URL_DEBUG: http://devcontainer:8888
      PROJECT_DIR: ${PWD:-/workspaces/refactored-winner}
      LOCAL_APPLICATION_TESTS_DIR: ${PWD:-/workspaces/refactored-winner}/application/tests
    env_file:
      - .env
    volumes:
      - ${PWD:-/workspaces/refactored-winner}:${PWD:-/workspaces/refactored-winner}:cached
    networks:
      dev:
    working_dir: ${PWD:-/workspaces/refactored-winner}/application/tests
    tty: true
    command: |
      bash -c '

      sleep infinity
      '
