networks:
  dev:
    driver: bridge
volumes:
  firebase-emulators-cache:
services:
  dev:
    # restart: unless-stopped
    container_name: dev
    image: ${BUILDER_IMAGE}
    entrypoint: dev-entrypoint.sh
    env_file:
      - .env
    environment:
      GOOGLE_APPLICATION_CREDENTIALS: ${GOOGLE_APPLICATION_CREDENTIALS:-/workspaces/refactored-winner/infra/gcloud-credentials.json}
      GOOGLE_CLOUD_PROJECT_ID: ${GOOGLE_CLOUD_PROJECT_ID}
      HOST_PWD: ${PWD:-/workspaces/refactored-winner}
    volumes:
      - ${PWD:-/workspaces/refactored-winner}:${PWD:-/workspaces/refactored-winner}:cached
      - /var/run/docker.sock:/var/run/docker.sock
    working_dir: ${PWD:-/workspaces/refactored-winner}
    command: |
      bash -c '
      # Ensure docker socket permissions
      make docker-sock
      make dev-local
      while true; do sleep 1000 ; done
      '
    networks:
      - dev

  backend:
    restart: unless-stopped
    image: ${APPLICATION_BACKEND_IMAGE:-europe-west1-docker.pkg.dev/moov-438615/docker-repository/utrade:backend-latest}
    build:
      context: ..
      dockerfile: application/backend/Dockerfile
      args:
        builder_image: ${BUILDER_IMAGE:-europe-west1-docker.pkg.dev/moov-438615/prod-docker-repository-public/moov-438615:builder-latest}

    env_file:
      - .env
    environment:
      GOOGLE_APPLICATION_CREDENTIALS: ${GOOGLE_APPLICATION_CREDENTIALS:-/workspaces/refactored-winner/infra/gcloud-credentials.json}
      FIREBASE_PROJECT_ID: ${FIREBASE_PROJECT_ID}
      FIREBASE_ADMINSDK_SERVICEACCOUNT_ID: ${FIREBASE_ADMINSDK_SERVICEACCOUNT_ID}
      UI_CONFIG_FIREBASE_SECRET_ID: ${UI_CONFIG_FIREBASE_SECRET_ID}
      UI_CONFIG_GOOGLEMAPS_SECRET_ID: ${UI_CONFIG_GOOGLEMAPS_SECRET_ID}
    volumes:
      - ${PWD:-/workspaces/refactored-winner}:${PWD:-/workspaces/refactored-winner}:cached
    networks:
      - dev

  firebase-emulators:
    restart: unless-stopped
    container_name: firebase-emulators
    image: ${BUILDER_IMAGE:-europe-west1-docker.pkg.dev/moov-438615/prod-docker-repository-public/moov-438615:builder-latest}
    # Cannot build while Dockerfile base image (see FROM ...) is using new local builder image (for conveniance and accuracy) that could not be pulled yet.
    # build: NOT
    env_file:
      - .env
    environment:
      FIREBASE_AUTH_EMULATOR_HOST: http://localhost:9099
      FIRESTORE_EMULATOR_HOST: http://localhost:8090
    volumes:
      - ${HOST_PWD:-${PWD:-/workspaces/refactored-winner}}:${PWD:-/workspaces/refactored-winner}:cached
      # - firebase-emulators-cache:/home/devuser/.cache/firebase/emulators
    working_dir: ${PWD:-/workspaces/refactored-winner}
    command: |
      bash -c '
      set -e
      trap "echo Exited with code $?." EXIT

      make local-firebase-emulators-install
      make local-firebase-emulators-start &

      # Need localproxy to forward some required port that could not be 
      # configured to listen on 0.0.0.0 from firebase.json file.
      TARGET_PORT=4400 LISTEN_PORT=4401 localproxy &
      until nc -z localhost 4500; do
        echo Waiting Firebase Emulator Reserved port at http://localhost:4500/ ;
        sleep 1 ;
      done
      TARGET_PORT=4500 LISTEN_PORT=4501 localproxy &
      until nc -z localhost 9299; do
        echo Waiting Firebase Emulator Reserved port 3 at http://localhost:9299/ ;
        sleep 1 ;
      done
      TARGET_PORT=9299 LISTEN_PORT=9399 localproxy &

      while true ; do sleep 1000 ; done
      '
    networks:
      dev:
  android-studio:
    restart: unless-stopped
    container_name: android-studio
    image: ${ANDROID_STUDIO_IMAGE:-europe-west1-docker.pkg.dev/moov-438615/docker-repository-public/utrade:android-studio-latest}
    env_file:
      - .env
    environment:
      DISPALY_RESOLUTION: "${DISPALY_RESOLUTION:-1440x900}"
    command: |
      bash -c 'while sleep 1000 ; do : ; done'
    # deploy:
    #   resources:
    #     reservations:
    #       devices:
    #         - driver: nvidia
    #           count: all
    #           capabilities: [gpu]
    volumes:
      - ${PWD:-/workspaces/refactored-winner}:${PWD:-/workspaces/refactored-winner}:cached
    working_dir: ${PWD:-/workspaces/refactored-winner}
    networks:
      dev:
