networks:
  dev:
    driver: bridge
volumes:
  firebase-emulators-cache:
services:
  dev:
    container_name: dev
    image: ${BUILDER_IMAGE:-us-central1-docker.pkg.dev/utrade-taxi-run-0/utrade-repository/utrade:dev-builder}
    build:
      context: .
      dockerfile: ./builder.Dockerfile
      args:
        - host_pwd=${PWD:-/workspaces/refactored-winner}
    entrypoint: dev-entrypoint.sh
    env_file:
      - .env
    environment:
      HOST_PWD: ${PWD:-/workspaces/refactored-winner}
      GOOGLE_CLOUD_PROJECT: ${UTRADE_GOOGLE_CLOUD_PROJECT_ID}
      GOOGLE_CLOUD_CREDENTIALS: ${UTRADE_GOOGLE_CLOUD_CREDENTIALS}
      TF_VAR_GOOGLE_MAPS_API_KEY: ${UTRADE_GOOGLE_MAPS_API_KEY}
      TF_VAR_GOOGLE_CLOUD_WEB_IDP_GOOGLE_OAUTH_SECRET: ${UTRADE_GOOGLE_CLOUD_WEB_IDP_GOOGLE_OAUTH_SECRET}
      # Firebase client SDK
      FIREBASE_FUNCTIONS_EMULATOR_HOST: http://firebase-emulators:5001
      FIREBASE_DATABASE_EMULATOR_HOST: http://firebase-emulators:9199
      # Firebase adminSDK
      FIREBASE_ADMINSDK_CREDENTIALS: ${UTRADE_FIREBASE_ADMINSDK_CREDENTIALS}
      FIREBASE_AUTH_EMULATOR_HOST: firebase-emulators:9099
      FIRESTORE_EMULATOR_HOST: firebase-emulators:8090
      UI_CONFIG_GOOGLE_MAPS_API_KEY: ${UTRADE_GOOGLE_MAPS_API_KEY}
      UI_CONFIG_FIREBASE_CONFIG: ${UTRADE_UI_CONFIG_FIREBASE_CONFIG}
    volumes:
      - ${PWD:-/workspaces/refactored-winner}:${PWD:-/workspaces/refactored-winner}:cached
      - /var/run/docker.sock:/var/run/docker.sock
    working_dir: ${PWD:-/workspaces/refactored-winner}
    command: |
      bash -c '
        make local-docker-compose-firebase-emulators-up
        while true; do sleep 1000 ; done
      '
    networks:
      - dev
    depends_on:
      - firebase-emulators
  firebase-emulators:
    container_name: firebase-emulators
    image: ${FIREBASE_EMULATORS_IMAGE:-us-central1-docker.pkg.dev/utrade-taxi-run-0/utrade-repository/utrade:dev-firebase-emulators}
    # Cannot build while Dockerfile base image (see FROM ...) is using new local builder image (for conveniance and accuracy) that could not be pulled yet.
    # build: NOT
    env_file:
      - .env
    environment:
      FIREBASE_AUTH_EMULATOR_HOST: http://localhost:9099
      FIRESTORE_EMULATOR_HOST: http://localhost:8090
    volumes:
      - ${HOST_PWD:-${PWD:-/workspaces/refactored-winner}}:${PWD:-/workspaces/refactored-winner}:cached
      # - firebase-emulators-cache:/home/devuser/.cache/firebase/emulators
    working_dir: ${PWD:-/workspaces/refactored-winner}
    command: |
      bash -c '
      set -e
      trap "echo Exited with code $?." EXIT

      make local-firebase-emulators-install
      make local-firebase-emulators-start &

      # Need proxy to forward some required port that could not be 
      # configured to listen on 0.0.0.0 from firebase.json file.
      TARGET_PORT=4400 LISTEN_PORT=4401 proxy &
      until nc -z localhost 4500; do
        echo Waiting Firebase Emulator Reserved port at http://localhost:4500/ ;
        sleep 1 ;
      done
      TARGET_PORT=4500 LISTEN_PORT=4501 proxy &
      until nc -z localhost 9299; do
        echo Waiting Firebase Emulator Reserved port 3 at http://localhost:9299/ ;
        sleep 1 ;
      done
      TARGET_PORT=9299 LISTEN_PORT=9399 proxy &

      while true ; do sleep 1000 ; done
      '
    networks:
      dev:
  vnc-android-studio:
    container_name: vnc-android-studio
    image: ${ANDROID_STUDIO_IMAGE:-us-central1-docker.pkg.dev/utrade-taxi-run-0/utrade-repository/utrade:vnc-android-studio}
    build:
      context: .
      dockerfile: ./local/android/vnc-studio.Dockerfile
    command: bash -c "while true; do sleep 1000 ; done "
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
    volumes:
      - ${PWD:-/workspaces/refactored-winner}:${PWD:-/workspaces/refactored-winner}:cached
    working_dir: ${PWD:-/workspaces/refactored-winner}
    networks:
      dev:
