networks:
  dev:
    driver: bridge
volumes:
  firebase-emulators-cache:
  clarinet_var_lib_docker:
services:
  dev:
    container_name: dev
    image: ${BUILDER_IMAGE}
    env_file:
      - .env
    environment:
      HOST_PWD: ${PWD:-/workspaces/refactored-winner}
    volumes:
      - ${PWD:-/workspaces/refactored-winner}:${PWD:-/workspaces/refactored-winner}:cached
      - /var/run/docker.sock:/var/run/docker.sock
      - /dev:/dev
      - /lib/modules:/lib/modules:ro
    privileged: true
    cap_add:
      - SYS_ADMIN
      - NET_ADMIN
    working_dir: ${PWD:-/workspaces/refactored-winner}
    command: |
      bash -c '
      # Ensure docker socket permissions
      make docker-sock
      make dev
      while true; do sleep 1000 ; done
      '
    networks:
      dev:
        aliases:
          - devcontainer

  backend:
    restart: unless-stopped
    image: ${APPLICATION_BACKEND_IMAGE:-europe-west1-docker.pkg.dev/moov-438615/docker-repository/utrade:backend-latest}
    build:
      context: ..
      dockerfile: application/backend/Dockerfile
      args:
        builder_image: ${BUILDER_IMAGE}

    env_file:
      - .env
    environment:
      GOOGLE_APPLICATION_CREDENTIALS: ${GOOGLE_APPLICATION_CREDENTIALS:-/workspaces/refactored-winner/.devcontainer/gcloud/infra/application_default_credentials.json}
      FIREBASE_PROJECT_ID: ${FIREBASE_PROJECT_ID:-moov}
      UI_CONFIG_FIREBASE_SECRET_ID: ${UI_CONFIG_FIREBASE_SECRET_ID:-projects/moov-dev-439608/secrets/firebase-config-web/versions/2}
      UI_CONFIG_GOOGLEMAPS_SECRET_ID: ${UI_CONFIG_GOOGLEMAPS_SECRET_ID:-projects/moov-dev-439608/secrets/google-maps-api-key/versions/1}
    volumes:
      - ${PWD:-/workspaces/refactored-winner}:${PWD:-/workspaces/refactored-winner}:cached
    networks:
      - dev

  firebase-emulators:
    container_name: firebase-emulators
    image: ${FIREBASE_EMULATORS_IMAGE:-europe-west1-docker.pkg.dev/moov-dev-439608/docker-repository-public/moov-dev-439608:firebase-emulators-latest}
    # Cannot build while Dockerfile base image (see FROM ...) is using new local builder image (for conveniance and accuracy) that could not be pulled yet.
    # build: NOT
    env_file:
      - .env
    environment:
      FIREBASE_AUTH_EMULATOR_HOST: http://localhost:9099
      FIRESTORE_EMULATOR_HOST: http://localhost:8090
    volumes:
      - ${HOST_PWD:-${PWD:-/workspaces/refactored-winner}}:${PWD:-/workspaces/refactored-winner}:cached
      # - firebase-emulators-cache:/home/devuser/.cache/firebase/emulators
    working_dir: ${PWD:-/workspaces/refactored-winner}

    networks:
      dev:

  clarinet-devnet:
    container_name: clarinet-devnet
    privileged: true
    tty: true
    image: ${CLARINET_DEVNET_IMAGE:-europe-west1-docker.pkg.dev/moov-dev-439608/docker-repository-public/moov-dev-439608:clarinet-latest}
    # Cannot build while Dockerfile base image (see FROM ...) is using new local builder image (for conveniance and accuracy) that could not be pulled yet.
    # build: NOT
    env_file:
      - .env
    environment:
      DOCKER_HOST: "unix:///run/user/1000/docker.sock"
    volumes:
      - /dev:/dev
      - /lib/modules:/lib/modules
      - ${HOST_PWD:-${PWD:-/workspaces/refactored-winner}}:${PWD:-/workspaces/refactored-winner}:cached
      - clarinet_var_lib_docker:/home/clarinet/.local/share/docker
    cap_add:
      - NET_ADMIN
      - SYS_ADMIN
    working_dir: ${PWD:-/workspaces/refactored-winner}
    command: |
      bash -c '
       set -eux
       while true ; do sleep 1000 ; done
      '
    networks:
      dev:
  android-studio:
    container_name: android-studio
    cap_add:
      - SYS_ADMIN
    image: ${ANDROID_STUDIO_IMAGE:-europe-west1-docker.pkg.dev/moov-dev-439608/docker-repository-public/moov-dev-439608:android-studio-latest}
    env_file:
      - .env
    environment:
      # DISPLAY_RESOLUTION: "2560x1600"
      DISPLAY_RESOLUTION: "1920x1080"
      CHROME_LOG_FILE: /tmp/chrome_debug.log
      ANDROID_STUDIO_LOG_LEVEL: DEBUG
    # deploy:
    #   resources:
    #     reservations:
    #       devices:
    #         - driver: nvidia
    #           count: all
    #           capabilities: [gpu]
    privileged: true
    volumes:
      - ${PWD:-/workspaces/refactored-winner}:${PWD:-/workspaces/refactored-winner}:cached
    devices:
      - /dev/kvm
    shm_size: "8gb"
    group_add:
      - render
      - sgx
    working_dir: ${PWD:-/workspaces/refactored-winner}
    command: |
      bash -c '
      studio & \
      while sleep 1000; do  : ; done'
    networks:
      dev:
  vault:
    image: hashicorp/vault:1.19
    cap_add:
      - IPC_LOCK
    environment:
      VAULT_DEV_ROOT_TOKEN_ID: root
      VAULT_DEV_LISTEN_ADDRESS: "0.0.0.0:8200"
    ports:
      - "8200:8200"
    volumes:
      - ./vault-data:/vault/file
    command: |
      vault login root

      vault policy write backend-policy ./policies/backend-policy.hcl

      vault kv put secret/firebase api_key=FAKE dev_id=123

      vault auth enable approle
      vault write auth/approle/role/backend-role \
          secret_id_ttl=60m \
          token_ttl=30m \
          token_max_ttl=60m \
          policies=backend-policy
    networks:
      dev:
