global:
  datacenter: vault-kubernetes-guide

client:
  enabled: true

server:
  replicas: 1
  bootstrapExpect: 1
  disruptionBudget:
    maxUnavailable: 0
  ui:
    enabled: false
  connectInject:
    enabled: false
  server:
    storage: 10Gi
