services:
  dev:
    container_name: dev
    build:
      context: ..
      dockerfile: .devcontainer/Dockerfile
      args:
        github_project_name: ${GITHUB_REPOSITORY_NAME:-refactored-winner}
        host_pwd: ${PWD:-/workspaces/${GITHUB_REPOSITORY_NAME:-refactored-winner}}
        builder_image: ${BUILDER_IMAGE:-us-central1-docker.pkg.dev/utrade-taxi-run-0/docker-repository-public/utrade:builder-latest}
    env_file:
      - .env
    environment:
      HOST_PWD: ${PWD:-/workspaces/${GITHUB_REPOSITORY_NAME:-refactored-winner}}
