services:
  dev:
    container_name: dev
    build:
      context: ..
      dockerfile: .devcontainer/Dockerfile
      args:
        github_project_name: ${GITHUB_REPOSITORY_NAME:-refactored-winner}
        host_pwd: ${PWD:-/workspaces/${GITHUB_REPOSITORY_NAME:-refactored-winner}}
        builder_image: ${BUILDER_IMAGE}
    env_file:
      - .env
    environment:
      HOST_PWD: ${PWD:-/workspaces/${GITHUB_REPOSITORY_NAME:-refactored-winner}}
      GOOGLE_CLOUD_CREDENTIALS: ${GOOGLE_CLOUD_CREDENTIALS}
