name: Build and Push new Version Tag Docker Images 

on:
  push:
    branches:
      - main

permissions:
  contents: write 

jobs:
  build-and-push-images:
    runs-on: self-hosted
    env:
      GCLOUD_PROJECT_ID: utrade-taxi-run-0

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0 
      - name: Define VERSION 
        run: | 
          git config --global user.name "GitHub Action"
          git config --global user.email "build-and-push-images-action@github.com"
          # Bump the version based on commit messages (default patch bump)
          standard-version
          echo "VERSION=$(git describe --tags --abbrev=7 --match 'v*')" >> $GITHUB_ENV
      - name: Use VERSION
        run: echo "Current version is ${{ env.VERSION }}"
      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v1
        with:
          credentials_json: ${{ secrets.GCLOUD_SERVICE_KEY }}
      - name: Set up Cloud SDK
        run: |
          gcloud config set project ${{ env.GCLOUD_PROJECT_ID }}
      - name: Configure Docker for GCR
        run: |
          gcloud auth configure-docker europe-west1-docker.pkg.dev
      - name: Set up Docker Buildx
        # uses: docker/setup-buildx-action@v3
        run: |
          make docker-buildx-setup
      - name: Bump version and push tags
        run: |
          # Push the new commit and the new tag
          git push --follow-tags origin main
      - name: Build and push up to date project images
        run: |
          make images-ci
