permissions:
  id-token: write
  contents: read
name: Build and Push Git Commit Tagged Docker Images To Dev environment
on:
  push:
    branches:
      - dev
jobs:
  dev-build-local-images:
    runs-on: self-hosted
    env:
      INFRA_ENV: dev
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0 # Maintenant, cela obtiendra tous les tags ainsi que les commits
      - name: Define VERSION
        run: |
          echo "VERSION=$(git describe --tags --abbrev=7 --match 'v*')" >> $GITHUB_ENV
      - name: Use VERSION
        run: echo "Current version is ${{ env.VERSION }}"
      - name: Authenticate to Google Cloud via Workload Identity Federation
        uses: google-github-actions/auth@v1
        with:
          workload_identity_provider: projects/203475703228/locations/global/workloadIdentityPools/github-pool/providers/github
          service_account: github-actions-main@moov-dev-439608.iam.gserviceaccount.com
          token_format: "access_token"
      - name: Set up Cloud SDK
        run: |
          make gcloud-config-set-project
      - name: Configure Docker for GCR
        run: |
          make gcloud-auth-docker
      - name: Set up Docker Buildx
        run: |
          make docker-buildx-setup
      - name: Build and load local project images
        run: |
          make images-ci
