name: Build and Push Docker Image

on:
  push:
    branches:
      - main
      - dev 

jobs:
  build-and-push:
    runs-on: self-hosted
    env:
      GCLOUD_PROJECT_ID: utrade-taxi-run-0

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v1
        with:
          credentials_json: ${{ secrets.GCLOUD_SERVICE_KEY }}

      - name: Set up Cloud SDK
        run: |
          gcloud config set project ${{ env.GCLOUD_PROJECT_ID }}

      - name: Configure Docker for GCR
        run: |
          gcloud auth configure-docker

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      # # Step 3: Log in to Docker Hub or GCR
      # - name: Log in to Google Container Registry
      #   run: echo "${{ secrets.GCLOUD_ACCESS_GITHUB_ACTIONS }}" | docker login -u _json_key --password-stdin https://gcr.io

      - name: Build Docker image
        run: |
          make builder-image
