name: Build and Push Docker Images

on:
  push:
    branches:
      - main
      - dev 

jobs:
  build-and-push-images:
    runs-on: self-hosted
    env:
      GCLOUD_PROJECT_ID: utrade-taxi-run-0

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0 # Maintenant, cela obtiendra tous les tags ainsi que les commits
      - name: Define GIT_HEAD_VERSION 
        run: echo "GIT_HEAD_VERSION=$(git describe --tags --abbrev=7 --match 'v*')" >> $GITHUB_ENV
      - name: Use GIT_HEAD_VERSION
        run: echo "Current version is ${{ env.GIT_HEAD_VERSION }}"
      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v1
        with:
          credentials_json: ${{ secrets.GCLOUD_SERVICE_KEY }}

      - name: Set up Cloud SDK
        run: |
          gcloud config set project ${{ env.GCLOUD_PROJECT_ID }}
      - name: Configure Docker for GCR
        run: |
          gcloud auth configure-docker us-central1-docker.pkg.dev
      - name: Set up Docker Buildx
        # uses: docker/setup-buildx-action@v3
        run: |
          make docker-buildx-setup

      - name: Build and push up to date project images
        run: |
          make images-ci
